repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: no-commit-to-branch # This hook prevents direct commits to main branch
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: []