services:
  esp-idf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minino-container
    volumes:
       - .:/project:z
    tty: true
    stdin_open: true
    working_dir: /project
    command: /bin/bash
    user: "501:20"
    environment:
      - HOME=/home/esp