on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
    contents: write
name: Build
jobs:
    build:
      strategy:
        fail-fast: true
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-tags: true
          fetch-depth: 0
  
      - name: Add version
        run: git describe --tags | sed 's/-[^-]*$//' > version.txt
  
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4
          target: esp32c6
          path: './firmware'
  
      - name: Rename artifact
        run: |
          ls -lah 
          cp build/minino.bin minino-esp32s3.bin
  
      - name: Archive Firmware Files
        uses: actions/upload-artifact@v3
        with: 
          name: esp32s3-firmware
          path: "*-esp32s3.bin"
  
    release:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Download Firmware Files
        uses: actions/download-artifact@v2
        with:
          path: release
      - name: Release Firmware
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/') 
        with:
          artifacts: release/*/*.bin
          generateReleaseNotes: true
          allowUpdates: true