on:
  push:    
    tags:        
      - 'v*'
  pull_request:

permissions:
  contents: write

name: Build

jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-tags: true
          fetch-depth: 0
  
      - name: Add version
        run: git describe --tags | sed 's/-[^-]*$//' > version.txt
  
      - name: esp-idf build NO OTA
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4-dev
          target: esp32c6
          path: './firmware'
          command: "idf.py @profiles/noota build"
      
      - name: Create NO OTA folder
        run: mkdir -p ./firmware/build-noota-release

      - name: Move NO OTA binaries
        run: |
          cp ./firmware/build-noota/*.bin ./firmware/build-noota-release/
          cp ./firmware/build-noota/*/*.bin ./firmware/build-noota-release/

      - name: esp-idf build OTA
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4-dev
          target: esp32c6
          path: './firmware'
          command: "idf.py @profiles/ota build"

      - name: Create OTA folder
        run: mkdir -p ./firmware/build-ota-release

      - name: Move OTA binaries
        run: |
          cp ./firmware/build-ota/*.bin ./firmware/build-ota-release/
          cp ./firmware/build-ota/*/*.bin ./firmware/build-ota-release/

      - name: Zip NO OTA Folder
        run: zip -r ./firmware/minino-noota-firmware.zip ./firmware/build-noota-release/

      - name: Zip OTA Folder
        run: zip -r ./firmware/minino-ota-firmware.zip ./firmware/build-ota-release/

      - name: Archive Firmware NO OTA ZIP
        uses: actions/upload-artifact@v4
        with: 
          name: minino-noota-firmware-zip
          path: "./firmware/minino-noota-firmware.zip"
      
      - name: Archive Firmware OTA ZIP
        uses: actions/upload-artifact@v4
        with: 
          name: minino-ota-firmware-zip
          path: "./firmware/minino-ota-firmware.zip"
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Firmware ZIP Files
        uses: actions/download-artifact@v4
        with:
          name: minino-noota-firmware-zip
          path: ./release/
      
      - name: Download OTA Firmware ZIP Files
        uses: actions/download-artifact@v4
        with:
          name: minino-ota-firmware-zip
          path: ./release/

      - name: Release Firmware
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/') 
        with:
          artifacts: release/minino-noota-firmware.zip,release/minino-ota-firmware.zip
          generateReleaseNotes: true
          allowUpdates: true
