# SPDX-FileCopyrightText: Copyright (c) 2024 Electronic Cats
#
# SPDX-License-Identifier: MIT

name: pre-commit

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - name: Set up repository
      uses: actions/checkout@v4
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1